### ISSUE TITLE
SparkIntervalTimer/SparkIntervalTimer.h: No such file or directory

### ISSUE THREAD

**Issue by jfl209** [ScruffR/ParticleSoftSerial#1]
Veryfing code using this library in Particle Build fails with this error:     ParticleSoftSerial/ParticleSoftSerial.h:38:53: fatal error: SparkIntervalTimer/SparkIntervalTimer.h: No such file or directory # include SparkIntervalTimer/SparkIntervalTimer.h ^

**Comment by ScruffR** [comment]
For later drivers by:
The reason for that error message is the dependency on a secondary library, which is mentioned in the README.md and sample code comments.

**Comment by jfl209** [comment]
Yeah, sorry about that. Saw that after I created the issue.  And, for what it's worth, the Particle Web  IDE definitely pushes you to create a ticket.

**Comment by ScruffR** [comment]
No problem! 
As said that comment was for clarity for future readers.
