### ISSUE TITLE
Build error for particle electron

### ISSUE THREAD

**Issue by kyuhyong** [ScruffR/ParticleSoftSerial#4]
Particle electron board is not supported?
I have issue with compiling the softSerial with SparkIntervalTimer/

**Comment by kyuhyong** [comment]
I was able to build the code however it does not seem to be working. 
I tried C0, C1 and D1, D2 combination but no luck. 
Also noticed that when softserial port is configured, system becomes much slower. 
Is there anything do be done?

**Comment by ScruffR** [comment]
In what way is this a build error?
Build errors would produce compiler messages, which ones do you see? 
Can you post them?
Have you tried the library examples?
What device OS version are you targeting on your Electron?
C1 cannot be RX pin as it shares the interrupt line with the internal RI_UC line (unfortunately that wasn't documented for the Electron before, but will be added soon).

---

Update: 
I've now tested and see some unexpected behaviour too - I'll investigate.
For the time being try 0.0.6 of that library

**Comment by ScruffR** [comment]
I have now publishde 0.0.11 which should work as expected again.
